# ****************************************************************************
# YANC build -- single source of truth for the compiler binaries.
#
# Used by Scripts/setup.sh, Scripts/setup.bat, Scripts/aurora.bat and the CI /
# release workflows, so the per-binary compile commands live in exactly one
# place. Works on Linux (native gcc) and on Windows under MSYS2 (where $(OS) is
# Windows_NT, which switches the output suffix to .exe).
#
#   make                build every binary into bin/
#   make <name>         build one: cmmcomp appcomp asmcomp cpppp cppcomp
#                       comp2gtkw gen_gtkw
#   make clean          remove bin/ and the flex/bison generated files
#   make install DESTDIR=<dir>   copy the binaries into <dir>/bin
#
# Override the toolchain or output dir, e.g.:
#   make CC=x86_64-w64-mingw32-gcc        # Windows standalone (no MSYS2 DLLs)
#   make BIN=out/bin                      # build into a different folder
# ****************************************************************************

CC     ?= gcc
BISON  ?= bison
FLEX   ?= flex
CFLAGS ?= -O2
LDLIBS ?= -lm
BIN    ?= bin

# Windows (incl. MSYS2) -> .exe suffix; POSIX -> none.
ifeq ($(OS),Windows_NT)
  EXE := .exe
else
  EXE :=
endif

CMM := Compilers/CMMComp/Sources
APP := Compilers/APPComp/Sources
ASM := Compilers/ASMComp/Sources
CPP := Compilers/CPPComp/Sources
SCR := Scripts
VERSION_H := Compilers/yanc_version.h

# Hand-written .c per binary (the flex/bison outputs lex.yy.c / y.tab.c are
# generated by the recipe and added to the compile line separately).
CMMCOMP_C := ast.c data_assign.c data_declar.c data_use.c itr.c diretivas.c \
             funcoes.c labels.c oper.c saltos.c stdlib.c t2t.c variaveis.c \
             array_index.c global.c macros.c messages.c args.c
APPCOMP_C := eval.c variaveis.c messages.c args.c
ASMCOMP_C := eval.c labels.c opcodes.c variaveis.c t2t.c hdl.c simulacao.c \
             array.c messages.c args.c
CPPCOMP_C := main.c messages.c types.c symtab.c ast.c codegen.c

BINARIES := $(BIN)/cmmcomp$(EXE) $(BIN)/appcomp$(EXE) $(BIN)/asmcomp$(EXE) \
            $(BIN)/cpppp$(EXE) $(BIN)/cppcomp$(EXE) \
            $(BIN)/comp2gtkw$(EXE) $(BIN)/gen_gtkw$(EXE)

.PHONY: all clean install \
        cmmcomp appcomp asmcomp cpppp cppcomp comp2gtkw gen_gtkw

all: $(BINARIES)

# Short phony aliases so `make cmmcomp` works regardless of the .exe suffix.
cmmcomp:   $(BIN)/cmmcomp$(EXE)
appcomp:   $(BIN)/appcomp$(EXE)
asmcomp:   $(BIN)/asmcomp$(EXE)
cpppp:     $(BIN)/cpppp$(EXE)
cppcomp:   $(BIN)/cppcomp$(EXE)
comp2gtkw: $(BIN)/comp2gtkw$(EXE)
gen_gtkw:  $(BIN)/gen_gtkw$(EXE)

$(BIN):
	mkdir -p $(BIN)

# --- cmmcomp (flex + bison) -------------------------------------------------
$(BIN)/cmmcomp$(EXE): $(addprefix $(CMM)/,$(CMMCOMP_C)) \
                      $(CMM)/CMMComp.l $(CMM)/CMMComp.y \
                      $(wildcard Compilers/CMMComp/Headers/*.h) $(VERSION_H) | $(BIN)
	cd $(CMM) && $(BISON) -y -d CMMComp.y && $(FLEX) CMMComp.l
	$(CC) $(CFLAGS) -o $@ $(addprefix $(CMM)/,$(CMMCOMP_C)) $(CMM)/lex.yy.c $(CMM)/y.tab.c $(LDLIBS)

# --- appcomp (flex) ---------------------------------------------------------
$(BIN)/appcomp$(EXE): $(addprefix $(APP)/,$(APPCOMP_C)) $(APP)/app.l \
                      $(wildcard Compilers/APPComp/Headers/*.h) $(VERSION_H) | $(BIN)
	cd $(APP) && $(FLEX) -o app.c app.l
	$(CC) $(CFLAGS) -o $@ $(APP)/app.c $(addprefix $(APP)/,$(APPCOMP_C)) $(LDLIBS)

# --- asmcomp (flex) ---------------------------------------------------------
$(BIN)/asmcomp$(EXE): $(addprefix $(ASM)/,$(ASMCOMP_C)) $(ASM)/ASMComp.l \
                      $(wildcard Compilers/ASMComp/Headers/*.h) $(VERSION_H) | $(BIN)
	cd $(ASM) && $(FLEX) -o ASMComp.c ASMComp.l
	$(CC) $(CFLAGS) -o $@ $(ASM)/ASMComp.c $(addprefix $(ASM)/,$(ASMCOMP_C)) $(LDLIBS)

# --- cpppp (single TU) ------------------------------------------------------
$(BIN)/cpppp$(EXE): $(CPP)/cpppp.c $(VERSION_H) | $(BIN)
	$(CC) $(CFLAGS) -Wall -o $@ $(CPP)/cpppp.c $(LDLIBS)

# --- cppcomp (flex + bison) -------------------------------------------------
$(BIN)/cppcomp$(EXE): $(addprefix $(CPP)/,$(CPPCOMP_C)) \
                      $(CPP)/CPPComp.l $(CPP)/CPPComp.y \
                      $(wildcard Compilers/CPPComp/Headers/*.h) $(VERSION_H) | $(BIN)
	cd $(CPP) && $(BISON) -y -d CPPComp.y && $(FLEX) CPPComp.l
	$(CC) $(CFLAGS) -Wall -Wno-unused-but-set-variable -Wno-unused-variable \
	      -Wno-unused-function -o $@ $(addprefix $(CPP)/,$(CPPCOMP_C)) \
	      $(CPP)/lex.yy.c $(CPP)/y.tab.c $(LDLIBS)

# --- GTKWave helpers --------------------------------------------------------
$(BIN)/comp2gtkw$(EXE): $(SCR)/comp2gtkw.c | $(BIN)
	$(CC) $(CFLAGS) -o $@ $(SCR)/comp2gtkw.c $(LDLIBS)

$(BIN)/gen_gtkw$(EXE): $(SCR)/gen_gtkw.c | $(BIN)
	$(CC) $(CFLAGS) -o $@ $(SCR)/gen_gtkw.c $(LDLIBS)

# --- housekeeping -----------------------------------------------------------
install: all
	mkdir -p "$(DESTDIR)/bin"
	cp $(BINARIES) "$(DESTDIR)/bin/"

clean:
	rm -rf $(BIN)
	rm -f $(CMM)/lex.yy.c $(CMM)/y.tab.c $(CMM)/y.tab.h
	rm -f $(APP)/app.c
	rm -f $(ASM)/ASMComp.c
	rm -f $(CPP)/lex.yy.c $(CPP)/y.tab.c $(CPP)/y.tab.h
