// ----------------------------------------------------------------------------
// global functions and variables of the compiler -----------------------------
// ----------------------------------------------------------------------------

#include <stdio.h>

// ----------------------------------------------------------------------------
// global variables -----------------------------------------------------------
// ----------------------------------------------------------------------------

extern FILE *yyin ;              // the .cmm needs to be linked to this bison pointer
extern FILE *f_asm;              // .asm file generated by the compiler
extern FILE *f_log;              // log file with project information
extern FILE *f_lin;              // memory in pc.v that shows the instructions in gtkwave

extern char dir_macro[1024];     // Macros directory
extern char dir_soft [1024];     // Software directory
extern char dir_tmp  [1024];     // Temp directory

// ----------------------------------------------------------------------------
// state variables ------------------------------------------------------------
// ----------------------------------------------------------------------------

extern int  acc_ok  ;            // 0 -> acc empty (use LOD), 1 -> acc loaded (use P_LOD)
extern int  line_num;            // parser-time: line the lexer is currently reading (used by MSG_ERR_*)
extern int  emit_line;           // emit-time:  line of the AST node generating the current instruction
                                 //             (set by stmt_emit / ast_emit_expr; read by add_instr)
extern char emit_fname[512];     // emit-time:  function whose body the walker is in (rem_fname display only)
extern int  num_ins ;            // number of parsed instructions (excluding final macros)
extern int  sim_arr ;            // tells whether the array is simulated or not

// ----------------------------------------------------------------------------
// interface functions --------------------------------------------------------
// ----------------------------------------------------------------------------

// parser start and end
void parse_init(char *f_name, char *prname, char *d_proc, char *d_macro, char *d_tmp, char *d_array);
void prog_emit (void);                              // fires from `fim : prog` action after parsing completes
void parse_end (char *prname, char *d_proc);

// registers the assembly instructions
void add_instr(char *inst, ...);           // standard
void add_sinst(int type, char *inst, ...); // special

// clears the peephole state inside add_instr (last_str + acc_name). Called at
// every basic-block boundary (labels, capture push/pop, macro use/end) so the
// "drop LOD x while the acc already holds x" optimization never crosses control
// flow.
void emit_peephole_reset(void);

// true when the accumulator is known to currently hold variable `name` -- lets
// codegen square the acc-resident half of c²+d² first so its LOD is dropped.
int  acc_holds(const char *name);
